INSERT INTO PUBLIC.RECIPE(ID,CREATE_DATE,INSTRUCTIONS,NAME,SUITABLE_PEOPLE_COUNT,IS_VEGETARIAN) VALUES
(1, TIMESTAMP '2021-12-23 00:00:00', 'asdsaas', 'Kofte', 321, FALSE);


INSERT INTO RECIPE VALUES
(2, TIMESTAMP '2021-12-23 00:00:00', 'asdsaas', 'Pirasa', 10, TRUE);

INSERT INTO PUBLIC.INGREDIENT (ID,NAME,RECIPE_ID) VALUES
(1,'DOMATES',1);

INSERT INTO PUBLIC.INGREDIENT (ID,NAME,RECIPE_ID) VALUES
(2,'KIYMA',1);

COMMIT;